import React from 'react'
import ProjectList from './ProjectList';
import "./Project.css"
const data=[
    {
        name:"Lead Genaration for VISHWA appication",
        des:"In the lead generation project for Sampath Bank PLC's banking app, VISHWA, I developed a machine learning solution to identify potential customers likely to engage with various banking products and services. Leveraging transactional behaviors such as credit card usage, debit card transactions, fixed deposit activities, and more, I employed advanced machine learning algorithms to predict leads effectively. Integrated with a user-friendly Streamlit frontend, the solution enabled real-time lead identification, enhancing Sampath Bank PLC's marketing strategies and facilitating targeted outreach to prospective customers.",
        projectlink:"#",
        tech:[
            {
                techName:"Machine learning"
            },
            {
                techName:"Python"
            },
            {
                techName:"Jupyter"
            },
            {
                techName:"Streamlit"
            },

        ]
    },
    {
        name:"Human Resource Management System ",
        des:"Developed an HRM database system, addressing personal information, absence management, and employee hierarchies. Implemented dynamic attributes, role-basedaccess control, and comprehensive reporting.",
        projectlink:"#",
        tech:[
            {
                techName:"Javascript"
            },
            {
                techName:"PHP"
            },
            {
                techName:"Mysql"
            },
            {
                techName:"Bootstrap"
            },

        ]
    },
    {
        name:"Custom LLM Based Science Q & A Web APP ",
        des:"The project involves developing a question answering system using LLMs. This project encompasses data processing, Natural Language Processing (NLP), and data analysis tocreate a model capable of answering questions generated by LLMs.",
        projectlink:"#",
        tech:[
            {
                techName:"Machine learning"
            },
            {
                techName:"Python"
            },
            {
                techName:"Reactjs"
            },
            {
                techName:"FastAPI"
            },
            {
                techName:"MongoDB"
            },

        ]
    },
];

function Project() {
  return (
    <div className='container project' id='projects'>
        <div className='section-title'>
            <h5>Projects</h5>
            <span className='line'></span>
        </div>

        <div  className='row'>
            {data.map((item,index)=>(
                <div className='col-xl-6 col-lg-6 col-md-6 col-sm-12' key={index}>
                    <ProjectList {...item}/>
                </div>
            ))}


        </div>
    </div>
  )
}

export default Project